os: osx
osx_image: xcode9.4
before_install:
  - brew update
  - brew outdated swiftlint || brew upgrade swiftlint
script:
  - xcodebuild -version
  - carthage version
  - swiftlint version
  - "./bootstrap.sh"
  - set -o pipefail && env "NSUnbufferedIO=YES" xcodebuild test -scheme WWDC -project WWDC.xcodeproj | xcpretty -f `xcpretty-travis-formatter`
